name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build -j 2
      - name: Test
        run: ctest --test-dir build --output-on-failure
